{% set name = "smartsheet-python-sdk" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d0ef0834b80838ef13493f0cf28374d11b72df278e870dc0f1a28a4567e763f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - pip
    - six >=1.9
    - setuptools
  run:
    - setuptools_scm
    - python >={{ python_min }}
    - requests
    - requests-toolbelt
    - six >=1.9
    - certifi
    - python-dateutil

test:
  imports:
    - smartsheet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://smartsheet-platform.github.io/api-docs/
  summary: Library that uses Python to connect to Smartsheet services (using API 2.0).
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
