{% set name = "smartsheet-python-sdk" %}
{% set version = "3.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/smartsheet_python_sdk-{{ version }}.tar.gz
  sha256: 2ce6ed7a2e69dc76273fb69ccacb8b6f2bd57aa0b5b72dbff9b8bbdc1e5303e8
  patches:
    - setup.py.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm >=7.0,<8
    - pip
    - six >=1.9
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - requests-toolbelt
    - six >=1.9
    - certifi
    - python-dateutil

test:
  imports:
    - smartsheet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://smartsheet-platform.github.io/api-docs/
  summary: Library that uses Python to connect to Smartsheet services (using API 2.0).
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
