{% set name = "smartsheet-python-sdk" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/smartsheet-python-sdk-{{ version }}.tar.gz
  sha256: 55265645c164fda177ff30d1c6d4eab43d496d5eccb292c33e8c806b522d3f48

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
    - six >=1.9
  run:
    - python >=3.8
    - requests
    - requests-toolbelt
    - six >=1.9
    - certifi
    - python-dateutil

test:
  imports:
    - smartsheet
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://smartsheet-platform.github.io/api-docs/
  summary: Library that uses Python to connect to Smartsheet services (using API 2.0).
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE.md

extra:
  recipe-maintainers:
    - rxm7706
